### ISSUE TITLE
River feedback: Team paragraph design

### ISSUE THREAD

**Issue by markwilliamfirth** [HackTrain/hacktrain.github.io#11]
Check This Out
https://www.dropbox.com/s/95j9pihozmes0ch/Screen%20Shot%202016-09-15%20at%2014.18.31.png?dl=0

Can we have the text kind of like the second spread below... But use a picture like the first one. This should go in the main page of the HackTrain.com site, and then link to a proper team page.

Which image would you like me to use?

**Comment by RiverTam57** [comment]
https://drive.google.com/a/hackpartners.com/file/d/0B8r7w_O10hsILXFLUUhNOTRnSnc/view?usp=sharing
https://drive.google.com/a/hackpartners.com/file/d/0B8r7w_O10hsILXFLUUhNOTRnSnc/view?usp=sharing

**Comment by RiverTam57** [comment]
Any of these.

**Comment by markwilliamfirth** [comment]
new issue overriding this
