### ISSUE TITLE
Press links

### ISSUE THREAD

**Issue by markwilliamfirth** [HackTrain/hacktrain.github.io#12]
Which press links would you like to feature @RiverTam57

**Comment by RiverTam57** [comment]
https://docs.google.com/spreadsheets/d/1MeTstrKTL-aUtfI58KuK6wgefI-OOnh9tMhqkjlaVzk/edit#gid=0

March - Rail Engineer
April - Tech World
June - Passenger Transport
Nov - Guardian
Nov - FT
Nov - RailPro
Nov - Railway-News

**Comment by markwilliamfirth** [comment]
Updated - closing issue
