### ISSUE TITLE
Team Page

### ISSUE THREAD

**Issue by RiverTam57** [HackTrain/hacktrain.github.io#28]
Hey Mark,

I've realised I simply haven't given you enough information about what exactly Alejandro and I think would work best for the team page.

Having looked at it again on the main website, it feels very out of place and not synced with the rest of the site (which looks very professional at the moment).

What I would like us to do is completely remove the team section on the front page and change the heading from "TEAM" to "ABOUT US"

In the About Us section we should have the full time kind of like this:

https://www.seesparkbox.com/team

**About Us**
We are a team of technology and startup professionals dedicated bringing the very best solutions that improve customer experience and operational efficiency into the rail industry. 

Each of us are dedicated to making a fundamental change in rail and will stop at nothing to deliver it. 

**The Hack Partners**

River + Alejandro top 2 as Co-Founders + CEO/CTO titles respectively
Then Mark, Damian, Phoebe with their titles
Then Will, Sarah + Ed with their titles

Then it would be nice to have "Advisory Board"

Matt
Adil
Toby

Below this we should have a "We're Hiring" section

Bid Writer + Administration Assistant

They should look like this:

https://www.codecademy.com/about/jobs

One should link to Unicorn Hunt (bid writer), the other one should probably link to a better suited site for that person.

**We're Hiring**

We're always on the look out for the very best and motivated individuals. If you want to be the bringer of change, then join us.

Bid Writer
Administration Assistant

**Comment by markwilliamfirth** [comment]
@RiverTam57 I've updated

**Comment by markwilliamfirth** [comment]
done
