### ISSUE TITLE
River feedback: Apply button font change

### ISSUE THREAD

**Issue by markwilliamfirth** [HackTrain/hacktrain.github.io#3]
change fonts for the boxes of "APPLY: EUROPEAN HACKTRAIN" and "APPLY: Hong Kong HackTrain"

**Comment by markwilliamfirth** [comment]
@RiverTam57 what kind of font would you like?

**Comment by axsauze** [comment]
Beside font change I would say to make them one-liners, as multiple line buttons are not very common

**Comment by markwilliamfirth** [comment]
@axsauze buttons have been made one liners

@RiverTam57 please specify font and whether to change for whole site or just buttons

**Comment by RiverTam57** [comment]
Buttons.

**Comment by markwilliamfirth** [comment]
which font would you like?

**Comment by RiverTam57** [comment]
Ask Will what his recommendation would be for fonts.

**Comment by markwilliamfirth** [comment]
Asked Will for fonts.

Have updated button font updated to "Brown" with "Montserrat" as backup
