### ISSUE TITLE
River feedback: Add imagery to services

### ISSUE THREAD

**Issue by markwilliamfirth** [HackTrain/hacktrain.github.io#4]
This is probably the weakest of all sections.

It's too easy... Not emotional enough. Doesn't show us off as much as we want to...

It should be a lot more visually compelling. Let's add in some really powerful imagery here.

**Comment by markwilliamfirth** [comment]
@RiverTam57 we need to update services to what we actually provide i.e. are we a hackathon services provider? I assume not, so should I remove all but digital transformation and add images? What kind of images would you like?

**Comment by axsauze** [comment]
For this one I think instead of having one section with a brief description of 3 services, we should have one section about the T.R.I.A.L. services itself, and one section with the hackathon, as the hackathon is not a service we provide, but an annual industry event we host

**Comment by RiverTam57** [comment]
I agree. we need to include a paragraph about the TRIAL framework. a paragraph about events (hackathons,  conferences, meet ups) and consultancy

**Comment by RiverTam57** [comment]
@markwilliamfirth talk to damian about paragraph for TRIAL.

he'll have something that he can  copy paste from.

**Comment by markwilliamfirth** [comment]
I have removed other services and added only T.R.I.A.L. as a service:

Our Transport and Rail Infrastructure Advancement Laboratory (T.R.I.A.L.) service provides an innovative framework to problem-solve in the rail industry. Working as a technology consultancy, we identify your organisation's challenges, run trials and feasibility studies to test solutions and after finding a successful solution, deliver it as a digital transformation project.

I will run it by damian

Alejandro said a separate section for the hackathon, but River said a separate section for (hackathons, conferences, meet ups) and consultancy. Which should we do?

**Comment by markwilliamfirth** [comment]
Have updated to Damian's feedback:

"Our Transport and Rail Infrastructure Advancement Laboratory (T.R.I.A.L.) service provides an innovative framework to solving problems in the rail industry. In the first step, we identify your organisation's challenges and set up a sandbox environment within your organisation. This will allow us to run accelerated trials and produce feasibility studies in a short period of time, compared to the industry standard. When the best solution to your challenges is found, we devise a business case for wider deployment, and deliver it as a digital transformation project."

**Comment by RiverTam57** [comment]
Something like that.....

**Comment by markwilliamfirth** [comment]
Updated - issue closed
