### ISSUE TITLE
River feedback: change our work image alignment

### ISSUE THREAD

**Issue by markwilliamfirth** [HackTrain/hacktrain.github.io#6]
Maybe reduce it to 6 and make the images bigger/aligned differently

**Comment by markwilliamfirth** [comment]
@RiverTam57 which 6 trials would you like to feature?

**Comment by markwilliamfirth** [comment]
Will update these

<img width="638" alt="screenshot 2016-09-16 11 51 30" src="https://cloud.githubusercontent.com/assets/5732209/18583682/ef8e9228-7c03-11e6-9741-37edfe4102e5.png">
[HackTrain Accelerator Case Study Short.pdf](https://github.com/HackTrain/hacktrain.github.io/files/476666/HackTrain.Accelerator.Case.Study.Short.pdf)

**Comment by markwilliamfirth** [comment]
Fixed

**Comment by RiverTam57** [comment]
Nice, will use this moving forward. Thanks
