### ISSUE TITLE
River feedback: Services to click through to another page

### ISSUE THREAD

**Issue by markwilliamfirth** [HackTrain/hacktrain.github.io#7]
It should be clickable to another page for people to read more about the work we've done.

**Comment by RiverTam57** [comment]
We don't need that style of design for the site, but just that level of the type of content would be nice

**Comment by markwilliamfirth** [comment]
@RiverTam57 are you sure you want both? Will take quite a while to make two designs.

It's quite easy to image one page vs multiple pages - it's just a matter of style

**Comment by RiverTam57** [comment]
Let's try the more detailed version then. Better to cut than to have to add more later.

**Comment by markwilliamfirth** [comment]
@RiverTam57 this issue is about multiple pages - what's the verdict? If trial descriptions need mroe detail we should open a separate issue for that

**Comment by RiverTam57** [comment]
Ahh, I see it as being a same issue as I just want the team page + services on separate pages rather than everything else.

**Comment by markwilliamfirth** [comment]
Override by other issue
