### ISSUE TITLE
River feedback: Team section paragraph

### ISSUE THREAD

**Issue by markwilliamfirth** [HackTrain/hacktrain.github.io#8]
Let's add an introductory paragraph about how we KNOW tech. We are technology specialists in rail.

**Comment by markwilliamfirth** [comment]
@RiverTam57 How about:

"We know tech. We are a diverse team of digital specialists with a wealth of experience in the rail sector, hailing from Oxford, Cambridge, Manchester, Southampton and Sheffield universities. Together we've ran over 50 technology events and managed 10 digital transformation projects with a number of different clients."

**Comment by RiverTam57** [comment]
I like this a lot.

Let's run with it.

**Comment by RiverTam57** [comment]
[https://www.dropbox.com/s/95j9pihozmes0ch/Screen%20Shot%202016-09-15%20at%2014.18.31.png?dl=0](url)

Can we have the text kind of like the second spread below... But use a picture like the first one. This should go in the main page of the HackTrain.com site, and then link to a proper team page.

**Comment by markwilliamfirth** [comment]
Team paragraph added. Issue closed
