### ISSUE TITLE
River feedback: Improve get in touch section

### ISSUE THREAD

**Issue by markwilliamfirth** [HackTrain/hacktrain.github.io#9]
Get In Touch

This is fairly weak too... Let's see what other sites have done.

**Comment by markwilliamfirth** [comment]
Other examples:
http://thebakery.com/#get-in-touch
http://www.techstars.com/contact/
http://www.ey.com/UK/en/Home/Contact-Us
http://www.baesystems.com/en/contactus
http://silverrailtech.com/contact/

**Comment by axsauze** [comment]
If you want an actual contact form you will need a backend - otherwise it will have to be an mailto attribute

**Comment by markwilliamfirth** [comment]
What should we do @RiverTam57 ?

**Comment by RiverTam57** [comment]
Let's just do a @mailto for now to see if that converts better than the contact form.

**Comment by markwilliamfirth** [comment]
Ok if necessary I can do this, but would take some time. Let's close this for now
